version: "3.9"

services:
  frontend-pole-emploi:
    container_name: frontend-pole-emploi
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-pole-emploi:latest
    restart: unless-stopped
    ports:
      - "4173:80" #127.0.0.1:4173:80
    environment:
      - VITE_API_URL=https://api-emploi.pajdef.com/api