name: Node.js CI (Yarn) + Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ---------------- Build ----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

  # ---------------- Déploiement ----------------
  deploy:
    runs-on: ubuntu-latest
    needs: build # dépend du job build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/pole-emploi/frontend
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
            docker ps | grep frontend-pole-emploi